# Embeddings Configuration for Biocurator Mapper
# This file controls how ontology terms are embedded for vector search

# OpenAI Embedding Model Configuration
model:
  name: "text-embedding-3-small"  # Updated to recommended model
  dimensions: 1536      # Automatically set based on model
  
# Processing Configuration
processing:
  batch_size: 100       # Number of terms to process in each batch
  parallel_processing: true    # Enable concurrent batch processing
  retry_failed: true          # Retry failed embedding requests
  max_retries: 3              # Maximum number of retry attempts
  
# Text Fields to Include in Embeddings
vectorize_fields:
  name: 1.0           # Base weight for ontology term name
  definition: 0.8     # Slightly lower weight for definition
  synonyms: 0.6       # Lower weight for synonyms
  xrefs: 0.4          # Lowest weight for cross-references
  
# Ontology-Specific Embedding Settings
do_specific:
  synonym_types:
    exact_synonym: 1.0       # Highest weight for exact synonyms
    narrow_synonym: 0.8      # Slightly lower weight for narrow synonyms
    broad_synonym: 0.7       # Lower weight for broad synonyms
    related_synonym: 0.5     # Lowest weight for related synonyms
  
  hierarchy_depth_weight: true  # Consider ontology term hierarchy in weighting
  max_hierarchy_depth: 5        # Maximum hierarchy depth to consider
  
  # DO-specific metadata fields
  include_metadata:
    xref_sources: ["MESH", "ICD10CM", "SNOMEDCT", "OMIM"]  # Prioritized external references
    definition_required: true    # Skip terms without definitions
    include_obsolete: false      # Exclude obsolete DO terms
    
  # Text composition for embeddings
  text_composition:
    primary_text: "name"         # Use term name as primary text
    context_fields: ["definition", "synonyms"]  # Additional context
    separator: " | "             # Field separator
    max_text_length: 8000        # Maximum characters per embedding
    
  # Quality filters
  quality_filters:
    min_definition_length: 10    # Minimum definition character count
    exclude_patterns: ["deprecated", "obsolete"]  # Patterns to exclude from text
  
# Text Preprocessing Options
preprocessing:
  lowercase: false            # Convert text to lowercase
  remove_punctuation: false   # Remove punctuation marks
  combine_fields_separator: " | "  # Separator when combining multiple fields
  
# Performance Settings
performance:
  request_timeout: 30         # Timeout for OpenAI API requests (seconds)
  rate_limit_delay: 0.1      # Delay between API requests (seconds)
  
# Cost and Usage Tracking
usage:
  track_tokens: true         # Track token usage for cost estimation
  log_requests: false        # Log individual embedding requests (for debugging)
  estimated_cost_per_1k_tokens: 0.00010  # Current OpenAI pricing